const express=require('express');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const app=express();
app.use(express.json({limit:'2mb'}));
app.use(express.static(__dirname));
const DB_FILE=path.join(__dirname,'data','db.json');
fs.mkdirSync(path.dirname(DB_FILE),{recursive:true});
function freshDB(){return {adminPassword:'ADMIN',members:[],pins:[],messages:[],leveltrackRequests:[],leveltrackUpgrades:[],leveltrackPayments:[],leveltrackMessages:[]};}
function save(d){fs.writeFileSync(DB_FILE,JSON.stringify(d,null,2))}
function load(){try{const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));Object.assign(d,{members:[],pins:[],messages:[],leveltrackRequests:[],leveltrackUpgrades:[],leveltrackPayments:[],leveltrackMessages:[]},{});d.members=d.members||[];d.pins=d.pins||[];d.messages=d.messages||[];d.leveltrackRequests=d.leveltrackRequests||[];d.leveltrackUpgrades=d.leveltrackUpgrades||[];d.leveltrackPayments=d.leveltrackPayments||[];d.leveltrackMessages=d.leveltrackMessages||[];return d}catch(e){const d=freshDB();save(d);return d}}
let db=load();
function rid(prefix){return prefix+'-'+crypto.randomBytes(4).toString('hex').toUpperCase()}
function memberId(){return 'B5-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function pin(){return 'B5-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function memberPublic(m){return {memberId:m.memberId,name:m.name,mobile:m.mobile,status:m.status,referral:m.referral,level:Number(m.level||1),levelMemberId:m.levelMemberId||null,joinedAt:m.joinedAt||m.registeredAt||null,upgradeDate:m.upgradeDate||null}}
function findMember(q){q=String(q||'').toLowerCase();return db.members.filter(m=>(m.name+' '+m.memberId+' '+m.mobile).toLowerCase().includes(q))}
function direct(id){return db.members.filter(m=>m.referral===id)}
function tree(rootId){const root=db.members.find(m=>m.memberId===rootId);if(!root)return {name:'நீங்கள்',id:'Not Registered',children:[]};const kids=id=>db.members.filter(m=>m.referral===id).map(m=>({name:m.name,id:m.memberId,mobile:m.mobile,level:Number(m.level||1),children:kids(m.memberId)}));return {name:root.name,id:root.memberId,mobile:root.mobile,level:Number(root.level||1),children:kids(root.memberId)}}
function descendants(rootId){let levels={1:[],2:[],3:[],4:[],5:[],6:[],7:[]},current=[rootId];for(let l=1;l<=7;l++){const next=db.members.filter(m=>current.includes(m.referral)).map(m=>m.memberId);levels[l]=db.members.filter(m=>next.includes(m.memberId));current=next;if(!current.length)break}return levels}
function wallet(memberId){const ps=db.pins.filter(p=>p.assignedTo===memberId);return {received:ps.length,used:ps.filter(p=>p.status==='USED').length,available:ps.filter(p=>p.status==='AVAILABLE').length,pins:ps.slice(-100)}}
function levelRule(level){return {1:1000,2:3000,3:20000,4:100000,5:200000,6:500000,7:0}[level]||0}
function latestUpgrade(memberId){return db.leveltrackUpgrades.filter(u=>u.memberId===memberId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]||null}
function leveltrackMemberData(id){const m=db.members.find(x=>x.memberId===id);if(!m)return null;const upgrade=latestUpgrade(id);const requests=db.leveltrackRequests.filter(r=>r.memberId===id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const incoming=db.leveltrackPayments.filter(p=>p.receiverMemberId===id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return {member:memberPublic(m),directReferrals:direct(id).length,totalDownline:(function count(x){let n=0;for(const c of direct(x)){n++;n+=count(c.memberId)}return n})(id),tree:tree(id),upgrade,requests,incomingPayments:incoming,history:db.leveltrackUpgrades.filter(u=>u.memberId===id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))} }
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'member.html')));
app.get('/member.html',(req,res)=>res.sendFile(path.join(__dirname,'member.html')));
app.get('/admin.html',(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));
app.post('/api/admin/login',(req,res)=>{if(req.body.password!==db.adminPassword)return res.status(401).json({error:'Incorrect password'});res.json({ok:true})});
app.post('/api/admin/password',(req,res)=>{if(req.body.oldPassword!==db.adminPassword)return res.status(401).json({error:'Current password is incorrect'});db.adminPassword=String(req.body.newPassword||'');save(db);res.json({ok:true})});
app.get('/api/admin/dashboard',(req,res)=>{const today=new Date().toISOString().slice(0,10);const total=db.members.length,pending=db.members.filter(m=>m.status==='Pending').length,verified=db.members.filter(m=>m.status==='Verified'||m.status==='Approved'||m.status==='Active').length;const report=db.members.map(m=>{const w=wallet(m.memberId);return {name:m.name,memberId:m.memberId,received:w.received,used:w.used,available:w.available}});const sent=db.pins.filter(p=>p.assignedTo).length,used=db.pins.filter(p=>p.status==='USED').length,leaders=new Set(db.pins.filter(p=>p.assignedTo).map(p=>p.assignedTo)).size;res.json({total,pending,verified,todayRegistrations:db.members.filter(m=>String(m.registeredAt||m.joinedAt||'').slice(0,10)===today).length,members:db.members.map(memberPublic),pinSummary:{sent,used,leaders},pinReport:report,upgradeRequests:db.leveltrackRequests.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),upgradePayments:db.leveltrackPayments.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))});});
app.get('/api/admin/members',(req,res)=>res.json({members:findMember(req.query.q).map(memberPublic)}));
app.get('/api/admin/member-details/:id',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id);if(!m)return res.status(404).json({error:'Member not found'});res.json({member:m,directReferrals:direct(m.memberId).length,totalDownline:(function count(x){let n=0;for(const c of direct(x)){n++;n+=count(c.memberId)}return n})(m.memberId),tree:tree(m.memberId)});});
app.post('/api/admin/member-status',(req,res)=>{const m=db.members.find(x=>x.memberId===req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});m.status=req.body.status;save(db);res.json({ok:true,member:memberPublic(m)})});
app.post('/api/admin/message',(req,res)=>{const msg=String(req.body.message||'').trim();if(!msg)return res.status(400).json({error:'Message is required'});if(req.body.to==='all')db.messages.push({to:'ALL',message:msg,at:new Date().toISOString()});else{if(!db.members.some(m=>m.memberId===req.body.memberId))return res.status(404).json({error:'Member not found'});db.messages.push({to:req.body.memberId,message:msg,at:new Date().toISOString()})}save(db);res.json({ok:true})});
app.get('/api/member/messages/:id',(req,res)=>{const msgs=[...db.messages.filter(x=>x.to===req.params.id||x.to==='ALL'),...db.leveltrackMessages.filter(x=>x.to===req.params.id)].sort((a,b)=>String(b.at).localeCompare(String(a.at)));res.json({messages:msgs})});
app.post('/api/admin/pins/generate',(req,res)=>{const m=db.members.find(x=>x.memberId===req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});const n=Math.min(500,Math.max(1,Number(req.body.quantity)||1)),out=[];for(let i=0;i<n;i++){let p=pin();while(db.pins.some(x=>x.pin===p))p=pin();const row={pin:p,assignedTo:m.memberId,status:'AVAILABLE',usedBy:null,createdAt:new Date().toISOString()};db.pins.push(row);out.push(row)}save(db);const w=wallet(m.memberId);res.json({pins:out,member:memberPublic(m),available:w.available,used:w.used})});
app.post('/api/member/send-otp',(req,res)=>{if(!/^\d{10}$/.test(String(req.body.mobile||'')))return res.status(400).json({error:'Invalid mobile number'});res.json({ok:true,otp:'123456'})});
app.post('/api/member/login',(req,res)=>{const m=db.members.find(x=>x.mobile===req.body.mobile);if(req.body.otp!=='123456')return res.status(401).json({error:'OTP சரியாக இல்லை'});if(!m)return res.status(404).json({error:'Member not found. Please register first.'});res.json({member:memberPublic(m)})});
app.post('/api/member/check-pin',(req,res)=>{const p=String(req.body.pin||'').toUpperCase();if(!db.pins.some(x=>x.pin===p&&x.status==='AVAILABLE'))return res.status(400).json({error:'Invalid or unavailable Joining PIN'});res.json({ok:true})});
app.post('/api/member/register',(req,res)=>{const b=req.body;if(db.members.some(m=>m.mobile===b.mobile))return res.status(409).json({error:'Mobile number already registered'});const p=String(b.pin||'').toUpperCase(),pr=db.pins.find(x=>x.pin===p&&x.status==='AVAILABLE');if(!pr)return res.status(400).json({error:'Invalid or unavailable Joining PIN'});if(b.referral!=='FIRST MEMBER'&&!db.members.some(m=>m.memberId===b.referral))return res.status(400).json({error:'Invalid Referral ID'});const m={...b,memberId:memberId(),status:'Pending',level:1,levelMemberId:null,registeredAt:new Date().toISOString()};delete m.pin;db.members.push(m);pr.status='USED';pr.usedBy=m.memberId;pr.usedAt=new Date().toISOString();save(db);res.json({member:memberPublic(m)})});
app.get('/api/member/dashboard/:id',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id);if(!m)return res.status(404).json({error:'Member not found'});const lv=descendants(m.memberId),w=wallet(m.memberId);const levels={};for(let i=1;i<=7;i++)levels[i]=lv[i].map(memberPublic);res.json({member:memberPublic(m),levels,tree:tree(m.memberId),wallet:w,upgradeData:leveltrackMemberData(m.memberId)})});
app.get('/api/member/level/:id/:level',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id),l=Number(req.params.level);if(!m||l<1||l>7)return res.status(404).json({error:'Not found'});const lv=descendants(m.memberId);res.json({members:lv[l].map(memberPublic)})});
app.post('/api/member/use-pin',(req,res)=>{const p=db.pins.find(x=>x.assignedTo===req.body.memberId&&x.status==='AVAILABLE');if(!p)return res.status(400).json({error:'No available PIN'});p.status='USED';p.usedBy=req.body.memberId;p.usedAt=new Date().toISOString();save(db);res.json({wallet:wallet(req.body.memberId)})});
// LevelTrack
app.get('/api/leveltrack/admin/dashboard',(req,res)=>{const levels={1:[],2:[],3:[],4:[],5:[],6:[],7:[]};db.members.forEach(m=>levels[Math.min(7,Math.max(1,Number(m.level||1)))].push(memberPublic(m)));res.json({levels,members:db.members.map(memberPublic),requests:db.leveltrackRequests.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),upgrades:db.leveltrackUpgrades.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),payments:db.leveltrackPayments.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))})});
app.get('/api/leveltrack/admin/member-details/:id',(req,res)=>{const d=leveltrackMemberData(req.params.id);if(!d)return res.status(404).json({error:'Member not found'});res.json(d)});
app.post('/api/leveltrack/member/upgrade-request',(req,res)=>{const m=db.members.find(x=>x.memberId===req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});const from=Number(m.level||1),to=from+1;if(from>=7)return res.status(400).json({error:'Level 7 is final level'});if(db.leveltrackRequests.some(r=>r.memberId===m.memberId&&r.status!=='Completed'))return res.status(400).json({error:'Upgrade request already pending'});const r={id:rid('LTR'),memberId:m.memberId,from,to,status:'Requested',date:new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()};db.leveltrackRequests.push(r);db.leveltrackMessages.push({to:'ADMIN',message:`New LevelTrack upgrade request: ${m.name} — L${from} → L${to}.`,at:new Date().toISOString()});save(db);res.json({ok:true,request:r})});
app.post('/api/leveltrack/admin/requests/:id/assign',(req,res)=>{const r=db.leveltrackRequests.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Upgrade request not found'});const m=db.members.find(x=>x.memberId===r.memberId);if(!m)return res.status(404).json({error:'Member not found'});const amount=Number(req.body.amount||levelRule(r.from));if(!amount)return res.status(400).json({error:'Upgrade amount required'});let u=db.leveltrackUpgrades.find(x=>x.requestId===r.id);if(!u){u={id:rid('LTU'),requestId:r.id,memberId:m.memberId,from:r.from,to:r.to,createdAt:new Date().toISOString()};db.leveltrackUpgrades.push(u)}Object.assign(u,{payee:String(req.body.payee||'').trim(),payeeId:String(req.body.payeeId||'').trim(),account:String(req.body.account||'').trim(),accountHolder:String(req.body.accountHolder||req.body.payee||'').trim(),bank:String(req.body.bank||'').trim(),ifsc:String(req.body.ifsc||'').trim(),upi:String(req.body.upi||'').trim(),amount,adminMessage:String(req.body.adminMessage||'').trim(),detailsSent:true,detailsSentAt:new Date().toISOString()});r.status='Approved - Payment Details Sent';db.leveltrackMessages.push({to:m.memberId,message:`Admin approved your L${r.from} → L${r.to} upgrade. Payment details are now available in Level Upgrade.`,at:new Date().toISOString()});save(db);res.json({ok:true,request:r,upgrade:u})});
app.post('/api/leveltrack/member/upgrade/:id/pay',(req,res)=>{const u=db.leveltrackUpgrades.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Upgrade not found'});if(u.memberId!==req.body.memberId)return res.status(403).json({error:'Not your upgrade'});if(!u.detailsSent)return res.status(400).json({error:'Payment details not sent yet'});const utr=String(req.body.utr||'').trim();if(!utr)return res.status(400).json({error:'UTR is required'});u.memberPaid=true;u.utr=utr;u.paidAt=new Date().toISOString();let p=db.leveltrackPayments.find(x=>x.upgradeId===u.id);if(!p){p={id:rid('LTP'),upgradeId:u.id,fromMemberId:u.memberId,receiverMemberId:u.payeeId,from:db.members.find(x=>x.memberId===u.memberId)?.name||u.memberId,to:u.payee||u.payeeId,amount:u.amount,utr,memberAccepted:false,adminApproved:false,createdAt:new Date().toISOString()};db.leveltrackPayments.push(p)}else{p.utr=utr;p.memberAccepted=false;p.adminApproved=false}if(u.payeeId)db.leveltrackMessages.push({to:u.payeeId,message:`Payment received for L${u.from} → L${u.to}. Please accept the payment.`,at:new Date().toISOString()});save(db);res.json({ok:true,upgrade:u,payment:p})});
app.post('/api/leveltrack/member/incoming/:id/accept',(req,res)=>{const p=db.leveltrackPayments.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Payment not found'});if(p.receiverMemberId!==req.body.memberId)return res.status(403).json({error:'Not your payment'});p.memberAccepted=true;p.acceptedAt=new Date().toISOString();const u=db.leveltrackUpgrades.find(x=>x.id===p.upgradeId);if(u)u.receiverApproved=true;save(db);res.json({ok:true,payment:p})});
app.post('/api/leveltrack/admin/upgrades/:id/final-approve',(req,res)=>{const u=db.leveltrackUpgrades.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Upgrade not found'});const p=db.leveltrackPayments.find(x=>x.upgradeId===u.id);if(!u.memberPaid||!p?.memberAccepted)return res.status(400).json({error:'Member payment and receiver acceptance are required'});p.adminApproved=true;u.adminApproved=true;u.completedAt=new Date().toISOString();const m=db.members.find(x=>x.memberId===u.memberId);m.level=Number(u.to);m.levelMemberId='L'+u.to+'-'+String(db.members.filter(x=>Number(x.level||1)===Number(u.to)).length+1).padStart(3,'0');m.upgradeDate=new Date().toISOString();m.status='Verified';const r=db.leveltrackRequests.find(x=>x.id===u.requestId);if(r)r.status='Completed';db.leveltrackMessages.push({to:m.memberId,message:`Level upgrade completed. You are now Level ${m.level}.`,at:new Date().toISOString()});save(db);res.json({ok:true,member:memberPublic(m),upgrade:u})});
app.get('/api/leveltrack/admin/daily-report',(req,res)=>{const date=String(req.query.date||new Date().toISOString().slice(0,10));const upgrades=db.leveltrackUpgrades.filter(u=>u.adminApproved&&String(u.completedAt||'').slice(0,10)===date).map(u=>({from:u.from,to:u.to,amount:u.amount,date:String(u.completedAt).slice(0,10),member:memberPublic(db.members.find(m=>m.memberId===u.memberId))}));res.json({date,count:upgrades.length,upgrades})});
app.get('/api/leveltrack/member/dashboard/:id',(req,res)=>{const d=leveltrackMemberData(req.params.id);if(!d)return res.status(404).json({error:'Member not found'});res.json(d)});
app.get('/api/leveltrack/member/messages/:id',(req,res)=>{const msgs=db.leveltrackMessages.filter(x=>x.to===req.params.id).sort((a,b)=>String(b.at).localeCompare(String(a.at)));res.json({messages:msgs})});
const PORT=process.env.PORT||10000;app.listen(PORT,'0.0.0.0',()=>console.log('BORNTOWIN5 running on '+PORT));
